[package]
name = "rust-regex-dsl-creator"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10"
regex-syntax = "0.8"
thiserror = "1.0"

[dev-dependencies]
tempdir = "0.3"
toml = "0.8"
serde = { version = "1.0", features = ["derive"] }
itertools = "0.13"
