name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
jobs:
  PostRelease:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dev
        uses: actions/checkout@master
        with:
          ref: main
          fetch-depth: 0
      - name: Get current version
        uses: SebRollen/toml-action@v1.2.0
        id: current-version
        with:
          file: 'Cargo.toml'
          field: 'package.version'
      - name: Tag main
        env:
          VERSION: ${{ steps.current-version.outputs.VERSION }}
        run: |
          git tag "v$VERSION"
      - name: Merge to dev
        run: |
          git checkout dev
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "Jawk post release bot"
          git merge origin/main
      - name: Bump version
        id: new-version
        env:
          VERSION: ${{ steps.current-version.outputs.VERSION }}
        run: |
          echo "NEW_VERSION=$(echo $VERSION | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)" >> "$GITHUB_OUTPUT"
      - name: Update version in main Cargo.toml
        uses: sandstromviktor/toml-editor@2.0.0
        with:
          file: "Cargo.toml"
          key: "package.version"
          value: ${{ steps.new-version.outputs.VERSION }}
      - name: Update version in derive Cargo.toml
        uses: sandstromviktor/toml-editor@2.0.0
        with:
          file: "rust-regex-dsl_derive/Cargo.toml"
          key: "package.version"
          value: ${{ steps.new-version.outputs.VERSION }}
      - name: Update version in creator Cargo.toml
        uses: sandstromviktor/toml-editor@2.0.0
        with:
          file: "rust-regex-dsl-creator/Cargo.toml"
          key: "package.version"
          value: ${{ steps.new-version.outputs.VERSION }}
      - name: Update creator version in main Cargo.toml
        uses: sandstromviktor/toml-editor@2.0.0
        with:
          file: "Cargo.toml"
          key: "dependencies.rust-regex-dsl-creator.version"
          value: ${{ steps.new-version.outputs.VERSION }}
      - name: Update dsl_derive version in main Cargo.toml
        uses: sandstromviktor/toml-editor@2.0.0
        with:
          file: "Cargo.toml"
          key: "dependencies.rust-regex-dsl_derive.version"
          value: ${{ steps.new-version.outputs.VERSION }}
      - name: Commit
        env:
          NEW_VERSION: ${{ steps.new-version.outputs.VERSION }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "Jawk post release bot"
          git add ./Cargo.toml ./rust-regex-dsl-creator/Cargo.toml ./rust-regex-dsl_derive/Cargo.toml
          git commit -m "$NEW_VERSION"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: dev
          tags: true
      - name: Create Pull request
        uses: peter-evans/create-pull-request@v6.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          title: "${{ steps.new-version.outputs.VERSION }}"
          branch: dev
